vars:
  REPOSITORY: "."
tasks:
  - name: "make-directory"
    steps:
      - cmd: "mkdir {{REPOSITORY}}/test"
        com: "Création d'un répertoire"
      - cmd: "sleep 4"
      - cmd: "curl https://google.com > {{REPOSITORY}}/test/file.txt"
        com: "On écrit dans un fichier"
  - name: "remove-directory"
    steps:
      - cmd: "rm -rf {{REPOSITORY}}/test"
        com: "Allez hop, ca dégage !"